# Create the namespace for Nextcloud
apiVersion: v1
kind: Namespace
metadata:
  name: nextcloud2
---
# HelmOperator CRDs installation if not already installed
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: helmreleases.helm.cattle.io
spec:
  group: helm.cattle.io
  names:
    kind: HelmRelease
    listKind: HelmReleaseList
    plural: helmreleases
    singular: helmrelease
  scope: Namespaced
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              chart:
                type: object
                properties:
                  name:
                    type: string
                  repository:
                    type: string
                  version:
                    type: string
              values:
                type: object
                additionalProperties: true
---
# Install the HelmRelease for Nextcloud
apiVersion: helm.cattle.io/v1
kind: HelmRelease
metadata:
  name: nextcloud
  namespace: nextcloud2
spec:
  chart:
    name: nextcloud
    version: "22.0.0"  # Use the desired version
    repository: https://nextcloud.github.io/helm/
  values:
    persistence:
      enabled: true
      existingClaim: nextcloud2-pvc  # Optional, you can define persistent storage here
    ingress:
      enabled: true
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.tls: "true"
      hosts:
        - host: nextcloud2.yourexampledomain.com
          paths:
            - /
      tls:
        - secretName: nextcloud2-tls
          hosts:
            - nextcloud2.yourexampledomain.com
