apiVersion: v1
kind: Namespace
metadata:
  name: nextcloud2
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: nextcloud2
  name: mariadb-secret-creator
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mariadb-secret-creator-binding
  namespace: nextcloud2
subjects:
  - kind: ServiceAccount
    name: default
    namespace: nextcloud2
roleRef:
  kind: Role
  name: mariadb-secret-creator
  apiGroup: rbac.authorization.k8s.io
