apiVersion: batch/v1
kind: Job
metadata:
  name: db-secret-generator
  namespace: nextcloud2
spec:
  template:
    spec:
      containers:
      - name: generate-password
        image: bitnami/kubectl:latest
        command:
          - /bin/sh
          - -c
          - |
            # Generate password that meets the required criteria
            PASSWORD=""
            while [ -z "$PASSWORD" ] || ! echo "$PASSWORD" | grep -q '[a-z]' || ! echo "$PASSWORD" | grep -q '[A-Z]' || ! echo "$PASSWORD" | grep -q '[0-9]' || ! echo "$PASSWORD" | grep -q '[_@#$%&*!]'; do
              PASSWORD=$(tr -dc 'A-Za-z0-9_@#$%&*!' </dev/urandom | head -c 12)
            done

            echo "Generated password: $PASSWORD"

            # Create the secret directly with the generated password (no file, pass variable directly)
            kubectl create secret generic mariadb-secret --namespace=nextcloud2 --from-literal=password="$PASSWORD"
      restartPolicy: Never
  backoffLimit: 4
